### ISSUE TITLE
A new acquistion link needs a definition

### ISSUE THREAD

**Issue by jce1028** [opds-community/specs#2]
5.2.1. Acquisition Relations

Acquisition relations describe the extent of the content referred to by an Acquisition Link or the manner in which that Resource may be acquired. This specification defines six Acquisition Relations, which all begin with “http://opds-spec.org/acquisition”:

    http://opds-spec.org/acquisition: A generic relation that indicates that the complete representation of the content Resource may be retrieved.
    http://opds-spec.org/acquisition/open-access: Indicates that the complete representation of the Resource can be retrieved without any requirement, which includes payment and registration.
    http://opds-spec.org/acquisition/borrow: Indicates that the complete representation of the content Resource may be retrieved as part of a lending transaction.
    http://opds-spec.org/acquisition/buy: Indicates that the complete representation of the content Resource may be retrieved as part of a purchase.
    http://opds-spec.org/acquisition/sample or preview: Indicates that a subset of the content Resource may be retrieved.
    http://opds-spec.org/acquisition/subscribe: Indicates that the complete representation of the content Resource may be retrieved as part of a subscription.

The above link relationships fail to provide an option for the a resource that is streamed or provided as part of a web reader.   

There should be an addendum or extension to this spec that accommodates a redirection of the browser or the opening of a web UI or browser window (e.g target new) to the supplied url where and application is loaded into the windows.

it could look like
 http://opds-spec.org/acquisition/view_online: A relation that indicates that the complete representation of the content Resource may be viewed online

**Comment by HadrienGardeur** [comment]
I don't really think that a new `rel` value is required for that.

If you borrow an audiobook that is available through a Web App, you can simply:

- use `http://opds-spec.org/acquisition/borrow` for the `rel`
- indicate `text/html` in `type`

**Comment by leonardr** [comment]
I agree with Hadrien; "view online" is a delivery format (`text/html`) that's compatible with any of the link relations.

The only thing I'd add is that practically, `text/html` can mean that you get the entire book as a single web page that you can save locally (as on Project Gutenberg), or it can mean that you load up a complex web application that shows you one page of the book at a time and only works when connected to the network (as with Overdrive Read).

To distinguish the "streaming" case from the "one big file" case we made up a value for the `profile` parameter, which we use internally. So this is how we talk about Overdrive Read, as opposed to the whole book in one big HTML file:

`text/html;profile="http://librarysimplified.org/terms/profiles/streaming-media"`

Hadrien, I'd be interested in any thoughts you have on this. For now, I'm going to close the issue; this is a case that's implemented in existing OPDS products.
